"""init

Revision ID: f23ae3107298
Revises:
Create Date: 2020-03-16 12:44:47.305388

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f23ae3107298"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rental_app_cars",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("registration_number", sa.String(length=255), nullable=True),
        sa.Column("color", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("registration_number"),
    )
    op.create_table(
        "rental_app_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column(
            "updated_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("car_id", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(length=255), nullable=False),
        sa.Column("rent_date", sa.Date(), nullable=True),
        sa.Column(
            "inquiry_at", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("has_settled", sa.Boolean(), server_default="false", nullable=True),
        sa.ForeignKeyConstraint(["car_id"], ["rental_app_cars.id"],),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rental_app_logs")
    op.drop_table("rental_app_cars")
    # ### end Alembic commands ###
