# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    env:
      POSTGRES_USER: car_rental
      POSTGRES_DB: car_rental
      POSTGRES_PASSWORD: password
      CR_DB_HOST: car_rental_db_test
      CR_DB_PORT: 5432

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Init db
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml up -d
          fi

      - name: Set up Python 3.6.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.6.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          pip install flake8
          pip install black==19.10b0
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
          black --check .

      - name: Coverage
        run: |
          pip install behave==1.2.6 coverage==5.0.3 pytest
          coverage run -m behave -k
          coverage run --append -m pytest
          coverage report
#  build:
#    needs: test
#    runs-on: ubuntu-latest
#
#    steps:
##    - uses: actions/checkout@v2
##    - name: Build the Docker image
##      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
#    - name: Set up Python 3.6.9
#      uses: actions/setup-python@v1
#      with:
#        python-version: 3.6.9
#    - name: Install dependencies
#      run: |
#        python -m pip install --upgrade pip
#        pip install -r requirements.txt
#    - name: Lint with flake8
#      run: |
#        pip install flake8
#        # stop the build if there are Python syntax errors or undefined names
#        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
#        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
#    - name: Test with pytest
#      run: |
#        pip install pytest
#        pytest
